management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
  servlet:
    context-path: /hs-kleinanzeigen
    port: 8081

spring:
  liquibase:
    change-log: classpath:/changeLog.xml
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: start01
    platform: mysql
    url: jdbc:mysql://localhost:4406/KLEINANZEIGEN?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
